local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<F5>", function()
  require("dap").continue()
end, opts)
vim.keymap.set("n", "<F10>", function()
  require("dap").step_over()
end, opts)
vim.keymap.set("n", "<F11>", function()
  require("dap").step_into()
end, opts)
vim.keymap.set("n", "<F12>", function()
  require("dap").step_out()
end, opts)
vim.keymap.set("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, opts)
vim.keymap.set("n", "<leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, opts)
vim.keymap.set("n", "<leader>dr", function()
  require("dap").repl.open()
end, opts)
vim.keymap.set("n", "<leader>dl", function()
  require("dap").run_last()
end, opts)
vim.keymap.set("n", "<leader>dd", function()
  require("dapui").toggle({ reset = true })
end, opts)
