name: CI
on:
  pull_request: 
    branches: [ develop ]
  push:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:
jobs:
  build-:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: cachix/install-nix-action@v16
      
      - uses: cachix/cachix-action@v10
        with:
          name: ttak0422
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # 参考 (https://github.com/kclejeune/system/blob/3b6cf43603870075c2ffc837c9461b70bc6cc7cd/bin/do.py)
      - run: |
          APFS_UTIL="/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util"
          echo 'run\tprivate/var/run' | sudo tee -a /etc/synthetic.conf
          $APFS_UTIL -B || true
          $APFS_UTIL -t || true
          
      - run: nix build .#darwinConfigurations.ci.system
      
      - run: ./result/sw/bin/darwin-rebuild switch --flake .#ci
