name: CI
on:
  pull_request: 
    branches: [ develop ]
  push:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:
jobs:
  build-:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: cachix/install-nix-action@v16
      
      - uses: cachix/cachix-action@v10
        with:
          name: ttak0422
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          
      - run: nix build .#darwinConfigurations.darwinIntel.system
      
      - run: ./result/sw/bin/darwin-rebuild switch --flake .#darwinIntel
